layer.cutout_mipped=createdeco:copper_catwalk createdeco:copper_catwalk_stairs createdeco:copper_support \
					createdeco:industrial_iron_catwalk createdeco:industrial_iron_catwalk_stairs createdeco:industrial_iron_support
