name: Create PBR
description: Simple PBR for Create mod.
author: Joshua Miller
input:
  format: raw
profiles:
- edition: Java
  format: 9
  name: Create LabPBR
  description: ''
  tags: 16x LabPBR
  encoding:
    format: lab-1.3
    opacity:
      texture: none
    color-red:
      texture: none
    color-green:
      texture: none
    color-blue:
      texture: none
  block-texture-size: 16
  item-texture-size: 16
- edition: Java
  format: 9
  name: Create OldPBR
  description: ''
  tags: 16x OldPBR
  encoding:
    format: old-pbr
    opacity:
      texture: none
    color-red:
      texture: none
    color-green:
      texture: none
    color-blue:
      texture: none
  block-texture-size: 16
  item-texture-size: 16
- edition: Java
  format: 9
  name: Create PatrixPBR 128x
  description: ''
  tags: 128x PatrixPBR
  encoding:
    format: lab-1.3
    opacity:
      texture: none
    color-red:
      texture: none
    color-green:
      texture: none
    color-blue:
      texture: none
    occlusion:
      texture: none
    normal-x:
      sampler: bicubic
    normal-y:
      sampler: bicubic
    normal-z:
      texture: normal
      color: blue
      sampler: bicubic
      min-value: 0
      max-value: 1
    metal:
      texture: specular
      color: green
    f0:
      texture: none
    hcm:
      texture: none
  block-texture-size: 128
  item-texture-size: 128
  texture-scale: 4
