name: Create PBR
description: Simple PBR for Create mod.
author: Joshua Miller
input:
  format: raw
profiles:
- edition: Java
  format: 8
  name: Create LabPBR
  description: ''
  tags: 16x LabPBR
  encoding:
    format: lab-1.3
    opacity:
      texture: none
    color-red:
      texture: none
    color-green:
      texture: none
    color-blue:
      texture: none
  block-texture-size: 16
  item-texture-size: 16
- edition: Java
  format: 8
  name: Create OldPBR
  description: ''
  tags: 16x OldPBR
  encoding:
    format: old-pbr
    opacity:
      texture: none
    color-red:
      texture: none
    color-green:
      texture: none
    color-blue:
      texture: none
  block-texture-size: 16
  item-texture-size: 16
