name: Release
on: workflow_dispatch

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: true

  publish_labPbr:
    name: Publish LabPbr
    runs-on: ubuntu-latest
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPBR
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: Create LabPBR
          zip: Create-LabPBR-v${{ github.run_number }}.zip
      - name: Release LabPBR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./Create-LabPBR-v${{ github.run_number }}.zip
          asset_name: Create-LabPBR-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Compile LabPBR WoodTracks
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-wood-track/project.yml
          profile: Create LabPBR Wood Tracks
          zip: Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
      - name: Release LabPBR-WoodTracks
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
          asset_name: Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Publish Wood-Tracks LabPBR to CurseForge
        uses: itsmeow/curseforge-upload@v3
        #if: github.event.inputs.publish_curseforge == 'true'
        with:
          display_name: Create LabPBR Wood-Tracks v${{ github.run_number }}
          file_path: Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
          changelog: "###Release ${{ github.run_number }}\n..."
          release_type: beta
          project_id: 682954
          game_endpoint: minecraft
          game_versions: "9366,9259,9186,9008,8857,8830,8203"
          token: ${{ secrets.CF_API_TOKEN }}
      - name: Publish LabPBR to CurseForge
        uses: itsmeow/curseforge-upload@v3
        #if: github.event.inputs.publish_curseforge == 'true'
        with:
          display_name: Create LabPBR v${{ github.run_number }}
          file_path: Create-LabPBR-v${{ github.run_number }}.zip
          changelog: "###Release ${{ github.run_number }}\n..."
          release_type: beta
          project_id: 682954
          game_endpoint: minecraft
          game_versions: "9366,9259,9186,9008,8857,8830,8203"
          token: ${{ secrets.CF_API_TOKEN }}
