name: Release
on: workflow_dispatch

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: true

  publish_labPbr:
    name: Publish LabPbr
    runs-on: ubuntu-latest
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPbr
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: Create LabPbr
          zip: Create-LabPbr-v${{ github.run_number }}.zip
      - name: Release LabPbr
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./Create-LabPbr-v${{ github.run_number }}.zip
          asset_name: Create-LabPbr-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Compile LabPbr WoodTracks
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-wood-track/project.yml
          profile: Create LabPbr Wood Tracks
          zip: Create-LabPbr-WoodTracks-v${{ github.run_number }}.zip
      - name: Release LabPbr-WoodTracks
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./Create-LabPbr-WoodTracks-v${{ github.run_number }}.zip
          asset_name: Create-LabPbr-WoodTracks-v${{ github.run_number }}.zip
          asset_content_type: application/zip
