name: Release
on: workflow_dispatch

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: true

  publish_labPbr:
    name: Publish LabPbr
    runs-on: ubuntu-latest
    needs: [prepare_release]
    steps:
      - uses: actions/checkout@v2
      - name: Compile LabPBR
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src/project.yml
          profile: Create LabPBR
          zip: Create-LabPBR-v${{ github.run_number }}.zip
      - name: Release LabPBR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./Create-LabPBR-v${{ github.run_number }}.zip
          asset_name: Create-LabPBR-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Compile LabPBR WoodTracks
        uses: null511/PixelGraph.GitHubAction@main
        with:
          project: src-wood-track/project.yml
          profile: Create LabPBR Wood Tracks
          zip: Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
      - name: Release LabPBR-WoodTracks
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
          asset_name: Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Publish to CurseForge, Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: Create-PBR v${{ github.run_number }}
          version: v${{ github.run_number }}
          version-type: beta
          changelog: "###Release v${{ github.run_number }}"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: CFeoJnHX
          modrinth-featured: true
          modrinth-loaders: minecraft
          modrinth-files-primary: Create-LabPBR-v${{ github.run_number }}.zip
          modrinth-files-secondary: Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
          curseforge-token: ${{ secrets.CF_API_TOKEN }}
          curseforge-id: 682954
          loaders: |
            fabric
            forge
            quilt
          files: |
            Create-LabPBR-v${{ github.run_number }}.zip
            Create-LabPBR-WoodTracks-v${{ github.run_number }}.zip
          dependencies: |
            create(optional){modrinth:LNytGWDc}
